version: '3'
services:
  step-functions:
    image: amazon/aws-stepfunctions-local
    volumes:
      - ./test/fixtures:/home/StepFunctionsLocal/fixtures:ro
    links:
      - aws-sam-local
    environment:
      SFN_MOCK_CONFIG: "/home/StepFunctionsLocal/fixtures/fixtures.json"
      WAIT_TIME_SCALE: 0
      LAMBDA_ENTRYPOINT: http://aws-sam-local:3001

  aws-sam-local:
    build:
      dockerfile: Dockerfile.samlocal
      context: .
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    command: sam local start-lambda --host 0.0.0.0 --docker-network step-function-iterator-network --container-host 172.24.0.1

  test-runner:
    image: node:16-buster
    volumes:
      - .:/app
    links:
      - step-functions
    working_dir: /app
    user: node
    command: npm run test

networks:
  default:
    name: step-function-iterator-network
