Transform: AWS::Serverless-2016-10-31

Resources:
  StateFunctionHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist.zip
      Handler: index.entrypoint
      Runtime: "nodejs14.x"
      Timeout: 25

  MySampleStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Definition:
        StartAt: GetElementCount
        States:
          GetElementCount:
            Type: Task
            Resource: !GetAtt StateFunctionHandler.Arn
            Parameters:
              "stateName.$": "$$.State.Name"
              "collection.$": "$.collection"

            ResultPath: "$.iterator"
            Next: CheckIfFinished
          CheckIfFinished:
            Type: Choice
            Choices:
              -
                Variable: "$.iterator.continue"
                BooleanEquals: true
                Next: ProcessElement
            Default: Done
          ProcessElement:
            Type: Task
            Resource: !GetAtt StateFunctionHandler.Arn
            ResultPath: "$.iterator"
            Parameters:
              "stateName.$": "$$.State.Name"
              "collection.$": "$.collection"
              "iterator.$": "$.iterator"

            Next: WaitABit
            Retry:
              - ErrorEquals:
                  - States.TaskFailed
                IntervalSeconds: 3
                MaxAttempts: 65535
                BackoffRate: 1.5
          WaitABit:
            Type: Wait
            Seconds: 10
            Next: CheckIfFinished
          Done:
            Type: Succeed

      Tracing:
        Enabled: true
      Role: !GetAtt [ StatesExecutionRole, Arn ]

  StatesExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - !Sub states.${AWS::Region}.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "lambda:InvokeFunction"
                Resource: "*"


Outputs:
  StateMachineArn:
    Value: !Ref MySampleStateMachine
